[package]
name = "niconeon-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
niconeon-domain = { path = "../niconeon-domain" }
serde.workspace = true
serde_json.workspace = true
