[package]
name = "niconeon-fetcher"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
niconeon-domain = { path = "../niconeon-domain" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
